apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapp-v6
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: testapp-v6.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testapp-v6
            port:
              number: 8080
